/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ExperienciasRouteImport } from './routes/experiencias'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ChefRouteImport } from './routes/chef'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExperienciasSlugRouteImport } from './routes/experiencias.$slug'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciasRoute = ExperienciasRouteImport.update({
  id: '/experiencias',
  path: '/experiencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefRoute = ChefRouteImport.update({
  id: '/chef',
  path: '/chef',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciasSlugRoute = ExperienciasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExperienciasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chef': typeof ChefRoute
  '/contato': typeof ContatoRoute
  '/experiencias': typeof ExperienciasRouteWithChildren
  '/sobre': typeof SobreRoute
  '/experiencias/$slug': typeof ExperienciasSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chef': typeof ChefRoute
  '/contato': typeof ContatoRoute
  '/experiencias': typeof ExperienciasRouteWithChildren
  '/sobre': typeof SobreRoute
  '/experiencias/$slug': typeof ExperienciasSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chef': typeof ChefRoute
  '/contato': typeof ContatoRoute
  '/experiencias': typeof ExperienciasRouteWithChildren
  '/sobre': typeof SobreRoute
  '/experiencias/$slug': typeof ExperienciasSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chef'
    | '/contato'
    | '/experiencias'
    | '/sobre'
    | '/experiencias/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chef'
    | '/contato'
    | '/experiencias'
    | '/sobre'
    | '/experiencias/$slug'
  id:
    | '__root__'
    | '/'
    | '/chef'
    | '/contato'
    | '/experiencias'
    | '/sobre'
    | '/experiencias/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChefRoute: typeof ChefRoute
  ContatoRoute: typeof ContatoRoute
  ExperienciasRoute: typeof ExperienciasRouteWithChildren
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencias': {
      id: '/experiencias'
      path: '/experiencias'
      fullPath: '/experiencias'
      preLoaderRoute: typeof ExperienciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chef': {
      id: '/chef'
      path: '/chef'
      fullPath: '/chef'
      preLoaderRoute: typeof ChefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencias/$slug': {
      id: '/experiencias/$slug'
      path: '/$slug'
      fullPath: '/experiencias/$slug'
      preLoaderRoute: typeof ExperienciasSlugRouteImport
      parentRoute: typeof ExperienciasRoute
    }
  }
}

interface ExperienciasRouteChildren {
  ExperienciasSlugRoute: typeof ExperienciasSlugRoute
}

const ExperienciasRouteChildren: ExperienciasRouteChildren = {
  ExperienciasSlugRoute: ExperienciasSlugRoute,
}

const ExperienciasRouteWithChildren = ExperienciasRoute._addFileChildren(
  ExperienciasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChefRoute: ChefRoute,
  ContatoRoute: ContatoRoute,
  ExperienciasRoute: ExperienciasRouteWithChildren,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
